import type { PurchaseRequest } from '@/types';

export const mockPurchaseRequests: PurchaseRequest[] = [
  // ===== 일반 구매 =====
  {
    id: 'PR-2025-001',
    category: 'general',
    title: '사무용 의자 구매',
    status: 'approved',
    createdAt: '2025-01-15T09:30:00Z',
    requester: '김철수',
    department: '경영지원팀',
    totalAmount: 2400000,
    details: {
      type: 'general',
      itemName: '허먼밀러 에어론 사무용 의자',
      quantity: 3,
      desiredDeliveryDate: '2025-02-15',
      budget: 2400000,
      reason: '신규 입사자 좌석 배치',
    },
  },
  {
    id: 'PR-2025-002',
    category: 'general',
    title: '회의실 프로젝터 구매',
    status: 'in_review',
    createdAt: '2025-01-20T14:00:00Z',
    requester: '이영희',
    department: '경영지원팀',
    totalAmount: 1500000,
    details: {
      type: 'general',
      itemName: 'EPSON EB-X51 프로젝터',
      quantity: 1,
      desiredDeliveryDate: '2025-02-28',
      budget: 1500000,
      reason: '3층 회의실 노후 장비 교체',
    },
  },
  {
    id: 'PR-2025-003',
    category: 'general',
    title: '업무용 책상 구매',
    status: 'pending',
    createdAt: '2025-02-01T10:15:00Z',
    requester: '박민수',
    department: '인사팀',
    totalAmount: 3600000,
    details: {
      type: 'general',
      itemName: '전동 높이조절 스탠딩 데스크',
      quantity: 6,
      desiredDeliveryDate: '2025-03-01',
      budget: 3600000,
      reason: '신규 채용 인원 업무 환경 구성',
    },
  },
  {
    id: 'PR-2025-004',
    category: 'general',
    title: '화이트보드 구매',
    status: 'rejected',
    createdAt: '2025-01-10T11:00:00Z',
    requester: '정다은',
    department: '마케팅팀',
    totalAmount: 450000,
    details: {
      type: 'general',
      itemName: '자석식 화이트보드 1200x900',
      quantity: 3,
      desiredDeliveryDate: '2025-01-25',
      budget: 450000,
      reason: '브레인스토밍 회의용',
    },
  },
  {
    id: 'PR-2025-005',
    category: 'general',
    title: '사무실 공기청정기',
    status: 'approved',
    createdAt: '2025-01-08T09:00:00Z',
    requester: '한지영',
    department: '경영지원팀',
    totalAmount: 890000,
    details: {
      type: 'general',
      itemName: '삼성 블루스카이 AX60T5080WFD',
      quantity: 2,
      desiredDeliveryDate: '2025-01-20',
      budget: 890000,
      reason: '미세먼지 시즌 대비 사무실 환경 개선',
    },
  },

  // ===== IT 자산 =====
  {
    id: 'PR-2025-006',
    category: 'it_asset',
    title: '개발팀 맥북 프로 구매',
    status: 'in_review',
    createdAt: '2025-01-25T13:30:00Z',
    requester: '최현우',
    department: '개발팀',
    totalAmount: 11200000,
    details: {
      type: 'it_asset',
      equipmentType: '노트북',
      specs: 'MacBook Pro M4 Pro, RAM 36GB, SSD 1TB',
      quantity: 4,
      user: '신규 개발자 4명',
      department: '개발팀',
    },
  },
  {
    id: 'PR-2025-007',
    category: 'it_asset',
    title: '외장 모니터 구매',
    status: 'approved',
    createdAt: '2025-01-18T10:00:00Z',
    requester: '김서연',
    department: '개발팀',
    totalAmount: 4800000,
    details: {
      type: 'it_asset',
      equipmentType: '모니터',
      specs: 'LG 32UN880 32인치 4K IPS',
      quantity: 8,
      user: '개발팀 전원',
      department: '개발팀',
    },
  },
  {
    id: 'PR-2025-008',
    category: 'it_asset',
    title: '업무용 노트북 구매',
    status: 'pending',
    createdAt: '2025-02-03T16:00:00Z',
    requester: '이준혁',
    department: '마케팅팀',
    totalAmount: 5600000,
    details: {
      type: 'it_asset',
      equipmentType: '노트북',
      specs: 'LG 그램 16, Intel i7, RAM 16GB, SSD 512GB',
      quantity: 4,
      user: '마케팅팀 신규 입사자',
      department: '마케팅팀',
    },
  },
  {
    id: 'PR-2025-009',
    category: 'it_asset',
    title: '서버 장비 교체',
    status: 'in_review',
    createdAt: '2025-01-28T11:30:00Z',
    requester: '오상현',
    department: '개발팀',
    totalAmount: 15000000,
    details: {
      type: 'it_asset',
      equipmentType: '서버/네트워크',
      specs: 'Dell PowerEdge R750, Xeon Gold 6330, 128GB RAM',
      quantity: 1,
      user: '인프라팀',
      department: '개발팀',
    },
  },
  {
    id: 'PR-2025-010',
    category: 'it_asset',
    title: '태블릿 구매',
    status: 'rejected',
    createdAt: '2025-01-12T09:45:00Z',
    requester: '윤소희',
    department: '마케팅팀',
    totalAmount: 2400000,
    details: {
      type: 'it_asset',
      equipmentType: '기타',
      specs: 'iPad Pro 13인치 M4, 256GB',
      quantity: 3,
      user: '디자인팀',
      department: '마케팅팀',
    },
  },

  // ===== MRO/소모품 =====
  {
    id: 'PR-2025-011',
    category: 'mro',
    title: 'A4 복사용지 구매',
    status: 'approved',
    createdAt: '2025-02-04T08:30:00Z',
    requester: '송미래',
    department: '경영지원팀',
    totalAmount: 120000,
    details: {
      type: 'mro',
      consumableName: 'A4 복사용지 80g (2,500매/박스)',
      quantity: 20,
      urgency: 'medium',
      deliveryAddress: '본사 3층 비품실',
    },
  },
  {
    id: 'PR-2025-012',
    category: 'mro',
    title: '토너 카트리지 구매',
    status: 'pending',
    createdAt: '2025-02-05T14:20:00Z',
    requester: '강도윤',
    department: '재무팀',
    totalAmount: 380000,
    details: {
      type: 'mro',
      consumableName: 'HP 라이저젯 토너 CF226X',
      quantity: 5,
      urgency: 'high',
      deliveryAddress: '본사 5층 재무팀',
    },
  },
  {
    id: 'PR-2025-013',
    category: 'mro',
    title: '사무용품 세트 구매',
    status: 'approved',
    createdAt: '2025-01-22T10:00:00Z',
    requester: '임수진',
    department: '인사팀',
    totalAmount: 85000,
    details: {
      type: 'mro',
      consumableName: '볼펜/스테이플러/포스트잇 세트',
      quantity: 30,
      urgency: 'low',
      deliveryAddress: '본사 2층 인사팀',
    },
  },
  {
    id: 'PR-2025-014',
    category: 'mro',
    title: '청소용품 구매',
    status: 'in_review',
    createdAt: '2025-02-02T09:00:00Z',
    requester: '배준서',
    department: '경영지원팀',
    totalAmount: 250000,
    details: {
      type: 'mro',
      consumableName: '청소용 세제/걸레/쓰레기봉투 세트',
      quantity: 10,
      urgency: 'medium',
      deliveryAddress: '본사 지하1층 관리실',
    },
  },
  {
    id: 'PR-2025-015',
    category: 'mro',
    title: '핸드 세니타이저 구매',
    status: 'pending',
    createdAt: '2025-02-06T11:15:00Z',
    requester: '조하늘',
    department: '인사팀',
    totalAmount: 150000,
    details: {
      type: 'mro',
      consumableName: '손세정제 500ml + 리필 1L',
      quantity: 50,
      urgency: 'high',
      deliveryAddress: '본사 전층 화장실/입구',
    },
  },
  {
    id: 'PR-2025-016',
    category: 'mro',
    title: '생수 정기 구매',
    status: 'approved',
    createdAt: '2025-01-30T08:00:00Z',
    requester: '노은채',
    department: '경영지원팀',
    totalAmount: 96000,
    details: {
      type: 'mro',
      consumableName: '제주 삼다수 2L (6개입/박스)',
      quantity: 40,
      urgency: 'low',
      deliveryAddress: '본사 각 층 탕비실',
    },
  },
];
